---
_hotel_id: HAR530
_portal_id: ''
latitude: 42.37292
longitude: -71.1218
name: Harvard Square Hotel
email: ''
phone_number: "--"
address:
  street1: 110 Mount Auburn Street
  street2: ''
  state: Massachusetts
  city: Cambridge
  country: United States
  zip_code: 02138
